### ISSUE TITLE
[radio] All radio buttons are checked on android

### ISSUE THREAD

**Issue by mengfanx8** [SmallStoneSK/rn-components-kit#1]
![screencap](https://user-images.githubusercontent.com/8436937/63210320-58d4d180-c11f-11e9-89f5-0906ab601558.png)

**Comment by SmallStoneSK** [comment]
@wallevy  示例代码是怎么写的？

**Comment by mengfanx8** [comment]
@SmallStoneSK 
```js
<Radio.Group
  onValueChange={set}
>
  {
    items.map(e => (
      <Radio.Button
        key={e}
        title={e}
        value={e}
        style={styles.radio}
        titleStyle={styles.title}
      />
    ))
  }
</Radio.Group>
```

**Comment by mengfanx8** [comment]
@SmallStoneSK 
It works fine when I set the animationType='none', maybe the animation has issue on android.

**Comment by SmallStoneSK** [comment]
@wallevy  have you ever run the example App on `Android`? Does it work fine?

**Comment by mengfanx8** [comment]
@SmallStoneSK 
Not work, my react-native version is 0.60.4

![9ed47a17-95f9-4da0-a9de-8fd60deec13c](https://user-images.githubusercontent.com/8436937/63211339-66db2000-c128-11e9-92f8-96ce57a290b0.png)

**Comment by SmallStoneSK** [comment]
@wallevy  well, I guess the problem is the usage of `Animated`. Code [here](https://github.com/SmallStoneSK/rn-components-kit/blob/master/packages/CheckBox/index.js#L51) shows the animated value's interpolation. If I change code like following, it works fine:

```js
dStyle = {
  ...StyleSheet.absoluteFillObject,
  opacity: this.opacityAnimatedValue.interpolate({inputRange: [0, 1], outputRange: [isSize ? 1 : 0.01, 1], extrapolate: 'clamp'}),
  transform: [{scale: this.sizeAnimatedValue.interpolate({inputRange: [0, 1], outputRange: [isOpacity ? 1 : 0.01, 1], extrapolate: 'clamp'})}]
};
this.unCheckedStyle = {
  ...StyleSheet.absoluteFillObject,
  opacity: this.opacityAnimatedValue.interpolate({inputRange: [0, 1], outputRange: [1, isSize ? 1 : 0.01], extrapolate: 'clamp'}),
  transform: [{scale: this.sizeAnimatedValue.interpolate({inputRange: [0, 1], outputRange: [1, isOpacity ? 1 : 0.01], extrapolate: 'clamp'})}]
};
```

I'll check this problem thses days~

**Comment by mengfanx8** [comment]
@SmallStoneSK 
Nice, thank you

PS What kind of kits would you like to collect in this repository?

**Comment by SmallStoneSK** [comment]
@wallevy 
Sorry to reply you so late, I have fixed the bug.

I want to collect widely used components in RN projects. Welcome PR~
