### ISSUE TITLE
can you provide  component that is Dialog and ListItem 

### ISSUE THREAD

**Issue by 25juan** [SmallStoneSK/rn-components-kit#2]
can you provide  component that is Dialog and ListItem . it doesn't seem.

**Comment by SmallStoneSK** [comment]
@25juan

Dialog组件是可以的，但是这封装出来会有一个大致的样式，不同的调用方可能有不同的自定义样式需求。所以封装出来的Dialog要么只有基础的show/close功能（会和Modal组件差不多），要么有一个公共样式（比较难符合所有调用方的样式要求）。

ListItem组件这个感觉没有封装的必要（我有参考其他很多的组件库，他们大多都有这个组件），但是我觉得大多数的调用方的ListItem组件样式都是不相同的（包括各种各样的布局或是最基础的padding，border之类的值）。所以即使我提供了这个组件，如果调用方要使用，他们可能还要覆盖我预先定义的样式。。。这个还不如调用方自己直接封装一个一次性的组件好了，成本差不多
