### ISSUE TITLE
this.setState 之后 数据改变了 但是dom Carousel的数量没有变化

### ISSUE THREAD

**Issue by thisSillyCow** [SmallStoneSK/rn-components-kit#4]
![image](https://user-images.githubusercontent.com/30546278/68000280-69b2cf00-fc9a-11e9-9dcc-1eccd057ad5b.png)
console的数据是有改变的 组件里面没有拿到 但是用其他的组件就是可以

**Comment by SmallStoneSK** [comment]
@thisSillyCow  给`Carousel`传一个`extra`属性，值就是你的`chapterDetail`。

**Comment by thisSillyCow** [comment]
![image](https://user-images.githubusercontent.com/30546278/68026306-50397380-fcea-11e9-8d66-5faee9c08576.png)
是这样子吗 还是不行

**Comment by thisSillyCow** [comment]
![image](https://user-images.githubusercontent.com/30546278/68026337-65ae9d80-fcea-11e9-96a4-733e33485475.png)

**Comment by SmallStoneSK** [comment]
@thisSillyCow `Carousel`组件内部是会用`React.cloneElement`复制`props.children`的，当你的数据源发生变化的时候，需要通知到`Carousel`组件，否则它感知不到。所以你需要再传一个字段`extra`就行，但是得确保你的`chapterDetail`前后两次是不同的数组对象，这样在`Carousel`的`componentWillReceiveProps`中会处理，重新`cloneElement`生成新的节点。
